name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
    branches:
      - master
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CRATE_NAME: rip2

jobs:
  nix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Test shell completions
        # pre-fetch bash-completion then get its path in the store
        run: nix build nixpkgs#bash-completion; BASH_COMPLETION_PKG=$(nix path-info nixpkgs#bash-completion) nix shell . nixpkgs#expect nixpkgs#bash-completion -c tests/shell_completions.exp
